
#! python3
import fdefs as f

f.setup()
f.enterWolt()
f.refresh()
f.booking(5,1,False)
f.booking(5,2,False)
f.booking(5,3,False)
f.booking(6,3,False)
f.booking(6,2,False)
f.booking(6,1,False)
f.booking(7,1,False)
f.booking(7,2,False)
f.booking(7,3,False)
f.booking(4,1,True)
f.booking(4,2,True)
f.booking(4,3,True)
f.booking(5,1,True)
f.booking(5,2,True)
f.booking(5,3,True)
f.booking(6,1,True)
f.booking(6,2,True)
f.booking(6,3,True)
f.booking(7,3,True)
f.booking(7,2,True)
f.booking(7,1,True)
f.pause()